// <auto-generated />
namespace Amazon.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class productImageUrlhasbeenadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productImageUrlhasbeenadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202110201615063_productImageUrl-has-been-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
